### ISSUE TITLE
where is install.sql file?

### ISSUE THREAD

**Issue by Alionides** [Hetachi/exiles#2]
Hello i cannot find mysql file

**Comment by Hetachi** [comment]
Sadly the mysql file was lost to the time, but based on registration.php file the table should contain the following columns:
id, (AUTO INCREMENT)
name, (VARCHAR)
password, (VARCHAR)
email, (VARCHAR)
race, (VARCHAR)
hp, (VARCHAR)
max_hp, (VARCHAR)
stamina, (VARCHAR)
stamina_max, (VARCHAR)
str, (VARCHAR)
agi, (VARCHAR)
vit, (VARCHAR)
money, (VARCHAR)
crystals, (VARCHAR)

Also note that the script was made for PHP version 5.4, which means you will need to do quite a bit of refactoring to make it work on a newer version.
